export const initialCategories = [
  "Landscapes",
  "Animals",
  "Portraits",
  "Architecture",
  "Food",
  "Nature",
  "Sports",
  "Cars",
  "People",
  "Flowers",
  "Seascapes",
  "Street photography",
  "Abstract",
  "Travel",
  "Weddings",
  "Fashion",
  "Wildlife",
  "Urban",
  "Sunsets",
  "Family",
  "Black and white",
  "Beaches",
  "Night photography",
  "Performance art",
  "Clouds",
  "Children",
  "Macro photography",
  "Interiors",
  "Fireworks",
  "Festivals",
  "Still life",
  "Mountains",
  "Forests",
  "Waterfalls",
  "Cityscapes",
  "Birds",
  "Skyscrapers",
  "Sunrises",
  "Musical instruments",
  "Artistic nudes",
  "Urban exploration",
  "Deserts",
  "Reflections",
  "Nature close-ups",
  "Cultural events",
  "Religious ceremonies",
  "Space and astronomy",
  "Vintage",
  "Fantasy and surreal",
  "Street art",
];
